version: "3.4"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Rk14101981"
      MYSQL_DATABASE: "imdbfavorites"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
